# Workflow 1


name: workflow-1
on:
  push:
    branches:
      - mika

jobs:
  my-job-1:
    runs-on: ubuntu-latest

    steps:
    - name: step-1
      run: |
        pwd
        echo "this is step-1"
    - name: step-2
      run: |
        ls
        uname -a
        echo "this is step-2"
